# -----------------------------------------------------
# Window rules
# -----------------------------------------------------

windowrule = tile on, match:title ^(Microsoft-edge)$
windowrule = tile on, match:title ^(Brave-browser)$
windowrule = tile on, match:title ^(Chromium)$
windowrule = float on, match:title ^(pavucontrol)$
windowrule = float on, match:title ^(blueman-manager)$
windowrule = float on, match:title ^(nm-connection-editor)$
windowrule = float on, match:title ^(qalculate-gtk)$

# Browser Picture in Picture
windowrule = float on, match:title ^(Picture-in-Picture)$
windowrule = pin on, match:title ^(Picture-in-Picture)$
windowrule = move 69.5% 4%, match:title ^(Picture-in-Picture)$

# idleinhibit
windowrule = idle_inhibit fullscreen,match:class ([window]) # Available modes: none, always, focus, fullscreen

#xwayland related rules
# when moving objects in resolve a large border is produced 
# This rule prevents that and serves as a template for any problematic xwayland apps
windowrule = no_blur on, match:class ^(\bresolve\b)$, match:xwayland true
# This is a general rule for xwayland apps but can have other consequences 
# for one user it impacted EMACs so it's disabled by default 
# It's here as a reference or for quick triage of xwayland ap
#windowrule = noblur, xwayland:1

# JetBrains rules
# fix tooltips (always have a title of `win.<id>`)
windowrule = no_initial_focus true, match:class ^(.*jetbrains.*)$, match:title ^(win.*)$
windowrule = no_focus true, match:class ^(.*jetbrains.*)$, match:title ^(win.*)$
# fix tab dragging (always have a single space character as their title)
windowrule = no_initial_focus true, match:class ^(.*jetbrains.*)$, match:title ^\\s$
windowrule = no_focus true, match:class ^(.*jetbrains.*)$, match:title ^\\s$
