# Don't intercept the following key strokes to make zsh-shift-select work.
map ctrl+shift+left no_op
map ctrl+shift+right no_op
map ctrl+shift+home no_op
map ctrl+shift+end no_op

# Don't intercept the following key strokes to make nvim split nav work.
map ctrl+H no_op
map ctrl+L no_op
